using System.Reflection;
using System.Runtime.InteropServices;

[assembly: Obfuscation(Exclude = false, Feature = "Apply to type *: apply to member * when method or constructor: virtualization")]
[assembly: Obfuscation(Exclude = false, Feature = "debug")]
[assembly: Obfuscation(Exclude = false, Feature = "encrypt resources")]
[assembly: Obfuscation(Exclude = false, Feature = "rename symbol names with printable characters")]
[assembly: Obfuscation(Exclude = false, Feature = "Apply to type *Impl: type renaming pattern 'roblox'.*")]
[assembly: Obfuscation(Exclude = true, Feature = "anonymous type properties renaming")]
[assembly: Obfuscation(Exclude = false, Feature = "sanitize resources")]
[assembly: Obfuscation(Exclude = false, Feature = "design-time usage protection")]
[assembly: Obfuscation(Exclude = false, Feature = "PEVerify")]
[assembly: Obfuscation(Exclude = false, Feature = "code control flow obfuscation")]
[assembly: AssemblyTitle("FB-CHECKER")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("")]
[assembly: AssemblyProduct("FB-CHECKER")]
[assembly: AssemblyCopyright("Copyright ©  2019")]
[assembly: AssemblyTrademark("")]
[assembly: ComVisible(false)]
[assembly: Guid("a31461ae-578b-450e-977a-78fa60e0c0dd")]
[assembly: AssemblyFileVersion("1.0.0.0")]
[assembly: AssemblyVersion("1.0.0.0")]
